# Generated by Django 3.2.6 on 2021-08-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aclab_productSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='', upload_to='Img/productImg'),
            preserve_default=False,
        ),
    ]
