# Generated by Django 3.2.6 on 2021-08-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aclab_productSystem', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='財產名稱'),
        ),
        migrations.AlterField(
            model_name='productuser',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
