# Generated by Django 3.2.6 on 2021-08-19 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aclab_productSystem', '0003_auto_20210819_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='time',
        ),
        migrations.AddField(
            model_name='productuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
