# Generated by Django 3.2.6 on 2021-08-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aclab_productSystem', '0004_auto_20210819_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuser',
            old_name='Product',
            new_name='key_Product',
        ),
    ]
