# Generated by Django 3.2.6 on 2021-09-06 08:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aclab_productSystem', '0006_book_bookborrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookborrow',
            options={'ordering': ['expired_date']},
        ),
        migrations.RenameField(
            model_name='bookborrow',
            old_name='created_at',
            new_name='establish_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='return_day',
        ),
        migrations.AddField(
            model_name='book',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='歸還日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookborrow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the book', primary_key=True, serialize=False),
        ),
    ]
